#!/usr/bin/env python3
"""Verify demo Media metadata points to objects generated by the MinIO seed image."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "infrastructure/media-seed/asset-manifest.txt"
MEDIA_SQL = ROOT / "data/seed-demo/postgresql/media.sql"
PRODUCT_ID_OFFSET = 1000


def normalize_product_id(raw_product_id: str) -> int:
    product_id = int(raw_product_id)
    return product_id + PRODUCT_ID_OFFSET if raw_product_id.startswith("0") else product_id


def normalized_object_keys() -> set[str]:
    keys: set[str] = set()
    pattern = re.compile(r"^products/(\d{4})/(.+)$")
    for raw_line in MANIFEST.read_text(encoding="utf-8").splitlines():
        relative_path = raw_line.strip()
        if not relative_path:
            continue
        match = pattern.fullmatch(relative_path)
        if not match:
            keys.add(f"seed/{relative_path}")
            continue
        product_id = normalize_product_id(match.group(1))
        keys.add(f"seed/products/{product_id}/{match.group(2)}")
    return keys


def database_object_keys() -> set[str]:
    sql = MEDIA_SQL.read_text(encoding="utf-8")
    return set(re.findall(r"'((?:seed/)?products/\d+/[^']+\.(?:avif|webp))'", sql))


def main() -> None:
    generated = normalized_object_keys()
    database = database_object_keys()

    missing = sorted(database - generated)
    unexpected = sorted(generated - database)

    if missing or unexpected:
        details: list[str] = []
        if missing:
            details.append("DB keys missing from generated seed:\n  " + "\n  ".join(missing[:20]))
        if unexpected:
            details.append("Generated keys missing from DB metadata:\n  " + "\n  ".join(unexpected[:20]))
        raise SystemExit("MEDIA_SEED_ALIGNMENT_FAILED\n" + "\n".join(details))

    required = {
        "seed/products/1001/original.webp",
        "seed/products/1001/thumbnail-240.avif",
        "seed/products/1001/home-480.avif",
        "seed/products/1001/search-640.avif",
        "seed/products/1001/detail-1600.webp",
    }
    absent = sorted(required - generated)
    if absent:
        raise SystemExit("MEDIA_SEED_REQUIRED_OBJECTS_MISSING\n  " + "\n  ".join(absent))

    products = {key.split("/")[2] for key in generated}
    print(
        "MEDIA_SEED_ALIGNMENT_OK "
        f"generated={len(generated)} database={len(database)} products={len(products)}"
    )


if __name__ == "__main__":
    main()
