apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-gateway
  template:
    metadata:
      labels:
        app: be-gateway
    spec:
      containers:
        - name: be-gateway
          image: marketplace/be-gateway:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: be-gateway-config
            - secretRef:
                name: be-gateway-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
