apiVersion: v1
kind: Secret
metadata:
  name: be-checkout-api-secret
type: Opaque
stringData:
  DB_PASSWORD: INJECT_FROM_CI_OR_EXTERNAL_SECRET
  SERVICE_CLIENT_SECRET: INJECT_FROM_CI_OR_EXTERNAL_SECRET
