apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-seller-outbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-seller-outbox
  template:
    metadata:
      labels:
        app: be-seller-outbox
    spec:
      containers:
        - name: be-seller-outbox
          image: marketplace/be-seller-outbox:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: be-seller-outbox-config
            - secretRef:
                name: be-seller-outbox-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
