-- Shared Oracle 23 deep-incident dataset. Run in a disposable schema.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lab_order_line PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lab_order_header PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE lab_outbox PURGE'; EXCEPTION WHEN OTHERS THEN NULL; END;/
CREATE TABLE lab_order_header(id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,seller_id NUMBER NOT NULL,customer_id NUMBER NOT NULL,status VARCHAR2(32) NOT NULL,created_at TIMESTAMP NOT NULL,payload CLOB);
CREATE TABLE lab_order_line(id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,order_id NUMBER NOT NULL,sku_id NUMBER NOT NULL,qty NUMBER NOT NULL,amount NUMBER(14,2) NOT NULL,description CLOB);
CREATE TABLE lab_outbox(id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,aggregate_id VARCHAR2(64) NOT NULL,status VARCHAR2(32) NOT NULL,created_at TIMESTAMP NOT NULL,processed_at TIMESTAMP,payload CLOB);
-- Seed with INSERT /*+ APPEND */ SELECT ... CONNECT BY LEVEL <= N in chunks.
-- Target >=2M headers, >=5M lines and >=2M outbox rows. seller_id=999 owns ~60% to force bind skew.
BEGIN DBMS_STATS.GATHER_SCHEMA_STATS(USER,estimate_percent=>DBMS_STATS.AUTO_SAMPLE_SIZE,method_opt=>'FOR ALL COLUMNS SIZE AUTO',cascade=>TRUE); END;/
