CREATE TABLE seller_settlement_ledger_entry (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id NUMBER NOT NULL,
  source_event_id VARCHAR2(128) NOT NULL UNIQUE,
  entry_type VARCHAR2(32) NOT NULL,
  amount NUMBER(19,2) NOT NULL,
  reference VARCHAR2(256) NULL,
  created_at TIMESTAMP NOT NULL
);
