apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-promotion-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be-promotion-api
  template:
    metadata:
      labels:
        app: be-promotion-api
    spec:
      containers:
        - name: be-promotion-api
          image: marketplace/be-promotion-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: be-promotion-api-config
            - secretRef:
                name: be-promotion-api-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
